### ISSUE TITLE
.bodyUsed vs. .locked

### ISSUE THREAD

**Issue by yutakahirano** [yutakahirano/fetch-with-streams#13]
The current draft states the following.

```
The bodyUsed attribute's getter must return if the read end of the body is locked.
```
That reflects discussion at https://github.com/slightlyoff/ServiceWorker/issues/452.

However, that may be problematic because the lock will be unlocked when the stream is closed or errored, if "the lock" behaves as same as an ExclusiveStreamReader defined at https://streams.spec.whatwg.org/#reader-class.
That means when an error happens in processing text() `.bodyUsed` will become false.

@tyoshino @domenic What do you think?

**Comment by yutakahirano** [comment]
One solution is to state that once the lock is acquired by `text()`, `arrayBuffer()`, `formData`, `blob()` and `json()`, it will never released even when the stream is closed or errored. Is it natural, and reasonable?

**Comment by yutakahirano** [comment]
Possible solutions...

1. To make the lock acquired by those methods unreleasable (i.e. https://github.com/yutakahirano/fetch-with-streams/issues/13#issuecomment-70475711).
1. `.bodyUsed` is no longer `isLocked`.
1. Reconsider the ExclusiveStreamReader spec again.
1. To make `.bodyUsed` accord with `isLocked`. This needs the fetch spec modification.

I don't like the second solution. Unifying consume body algorithm with other algorithms such as `pipeTo` is natural and reasonable. Having inconsistent multiple algorithms will confuse developers.

**Comment by domenic** [comment]
Yes, this is related to my question in https://github.com/slightlyoff/ServiceWorker/issues/452#issuecomment-69266089.

In short, I see two potential solutions:

- Remove `.bodyUsed` and just expose `.body.isLocked`
- Change the meaning of `bodyUsed` to not be related to locks but instead give you some idea whether the data in the stream has been read, as in https://github.com/slightlyoff/ServiceWorker/issues/452#issuecomment-56049602

**Comment by yutakahirano** [comment]
Thank you. I should have posted there. I close this issue and will post there.
