### ISSUE TITLE
Specify stream chunk type.

### ISSUE THREAD

**Issue by yutakahirano** [yutakahirano/fetch-with-streams#19]
Requested at https://github.com/slightlyoff/ServiceWorker/issues/452#issuecomment-73058012 by @wanderview.

**Comment by yutakahirano** [comment]
blocked by https://github.com/yutakahirano/fetch-with-streams/issues/17.

**Comment by wanderview** [comment]
Thanks Yutaka!

Can we also specify how the size of the ArrayBuffer is determined?  Is the UA free to chunk the data however it wishes?  Or does it have to return all available data in a single chunk when read() is called?

**Comment by yutakahirano** [comment]
> Is the UA free to chunk the data however it wishes?

Yes.
By the way, I'm planning to use [ReadableByteStream](https://github.com/whatwg/streams/blob/master/BinaryExtension.md) instead of ReadableStream when it gets stable enough (now it's not stable enough, so I will use ReadableStream for quite a while). It has `readInto()` function and the user can specify the buffer size with it.

**Comment by yutakahirano** [comment]
memo: I created a branch https://github.com/yutakahirano/fetch-with-streams/tree/use-arraybuffer-as-chunk for this issue. Its parent is https://github.com/yutakahirano/fetch-with-streams/tree/readable-stream-and-response which is a branch for #17.
