### ISSUE TITLE
"slow read" feature

### ISSUE THREAD

**Issue by annevk** [yutakahirano/fetch-with-streams#22]
In https://www.w3.org/Bugs/Public/show_bug.cgi?id=27781 @wanderview describes a "slow read" feature. That should probably be considered in the context of this repository.

**Comment by wanderview** [comment]
Incidentally, I asked about this in a related blink cr.  They indicated they intend to provide back-pressure to the network already.  So there would probably be no difference for a "slow-mode" in blink.

**Comment by yutakahirano** [comment]
As a blink developer, I plan to use server's "Cache-Control: no-store" header for the switch. When storing to cache, pulling data as soon as possible makes sense.

**Comment by annevk** [comment]
@yutakahirano that should probably make it into the final standard as a note of sorts or perhaps even a requirement. Note it in your document for now?

**Comment by yutakahirano** [comment]
@annevk, do you mean something like https://github.com/yutakahirano/fetch-with-streams/pull/23?

**Comment by annevk** [comment]
Yeah, something like that seems fine. I would probably mention the exact set of headers.

**Comment by yutakahirano** [comment]
@annevk Fixed. https://github.com/yutakahirano/fetch-with-streams/commit/683e0e17b74d3485cf812ce024077c0905ce9b9b

**Comment by annevk** [comment]
Thanks @yutakahirano!
