### ISSUE TITLE
Need to describe stream's chunk type more clearly

### ISSUE THREAD

**Issue by yutakahirano** [yutakahirano/fetch-with-streams#31]
Asked by @wanderview at #25.

> I think it would be better to define the Uint8Array chunk type where you define the stream concept for the object. Placing the chunk type down in ConsumeStream, etc makes it a bit hard to find.
Can you expand on what you means here?

**Comment by wanderview** [comment]
I mean change the text like this:

> A Response object has an associated readable stream (initially an empty ReadableByteStream).

To something like:

> A Response object has an associated readable stream (initially an empty ReadableByteStream).  This stream must produce chunks of type Uint8Array.

**Comment by yutakahirano** [comment]
Fixed. https://github.com/yutakahirano/fetch-with-streams/commit/fe6e7402e9f0e07861d09e9736f8495ad14d1770
