### ISSUE TITLE
Representing Fetch' body concept in streams, Response side

### ISSUE THREAD

**Issue by yutakahirano** [yutakahirano/fetch-with-streams#40]
Branched from #36. This is easier than the Request side counterpart (#41)

**Comment by gwicke** [comment]
The ability to stream composite responses from service workers would enable client-side page composition without hurting first-paint latency on slow connections.

**Comment by yutakahirano** [comment]
Please note that this is an internal issue for the spec (a.k.a. refactoring effort).

**Comment by tyoshino** [comment]
@gwicke Did you mean "streaming bytes composed in SW to the controlled page in response to fetch event" by "stream composite response"? Just wanna confirm.

**Comment by gwicke** [comment]
@yutakahirano, understood. I just wanted to provide feedback that basic enqueue functionality would already be very appealing for SW users. If there is an opportunity to release a small part of the spec including this for implementation, then that could be very useful to users.

@tyoshino: Yes, exactly. See https://phabricator.wikimedia.org/T106099 for our (Wikimedia Foundation / Wikipedia) use case.

**Comment by tyoshino** [comment]
@gwicke Thanks for the reply and sorry for delay. We're trying to work on it with higher priority. We do understand composability like this would be important feature for utilization of SW.

**Comment by yutakahirano** [comment]
merged https://github.com/yutakahirano/fetch-with-streams/commit/c3e058c561b19f00aa41a2776681d48266440eba
