### ISSUE TITLE
Do not conflate IDL ReadableStream and JS ReadableStream implicitly.

### ISSUE THREAD

**Issue by yutakahirano** [yutakahirano/fetch-with-streams#52]
Branched from #50.

We need to distinguish "fetch" (or "IDL") ReadableStream and "JavaScript" ReadableStream, and make their relationship clean.

**Comment by yutakahirano** [comment]
I think defining operations such as close and enqueue in the infrastructure section and using them from other parts are good for readability and modularity - We can say that we define IDL ReadableStream in the infrastructure section and we can move it to the WebIDL spec or the Streams spec later.
Even if we choose the first option of https://github.com/yutakahirano/fetch-with-streams/pull/50#issuecomment-126411742, handling ReadableStream as an IDL type in main fetch sections would be beneficial.

What do you think, @annevk, @domenic?

**Comment by annevk** [comment]
Yeah, having it in the infrastructure temporarily makes sense.

**Comment by domenic** [comment]
I guess this makes sense if you prefer saying "enqueue _idlChunk_ into _idlReadableStream_" instead of using EnqueueReadableStream directly on JS objects. It is probably a good refactoring.

**Comment by annevk** [comment]
Maybe we should open an issue against IDL for this?
