### ISSUE TITLE
Reuest.body value after passed to another Request

### ISSUE THREAD

**Issue by yutakahirano** [yutakahirano/fetch-with-streams#60]
```
req2 = new Request(req);
```

At https://github.com/whatwg/fetch/issues/61, we agreed that 
- `req.bodyUsed` should be false if `req` had null body, and
- `req.bodyUsed` should be true if `req` had a non-null body.

Anne proposed to introduce `obsolete flag` in order to make `req.body` null and `req.bodyUsed` true after passing the body, but it looks like another `passed flag` we replaced with ReadableStream.IsDisturbed. @jakearchibald's piping idea sounds cleaner to me and ideally it should work, but I'm not sure about its performance.

Thoughts?

cc: @domenic @wanderview @tyoshino

**Comment by yutakahirano** [comment]
cc: @annevk

**Comment by annevk** [comment]
I'm okay either way. I guess someone should measure the performance of doing piping if we are fine gating on that?

**Comment by domenic** [comment]
Is this solved currently? I lost track. If it is not, it probably can be solved similarly to https://github.com/slightlyoff/ServiceWorker/pull/934 ?

**Comment by yutakahirano** [comment]
It's not yet solved, and it should be solved as same as https://github.com/slightlyoff/ServiceWorker/pull/934.

**Comment by annevk** [comment]
What is the status of this issue? I missed it while merging in stream-based requests.
